CREATE DATABASE safiflow;
USE safiflow;
CREATE TABLE Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) DEFAULT NULL,
    DeviceID VARCHAR(255) NOT NULL,
    password VARCHAR(255) DEFAULT NULL,
    email VARCHAR(100) DEFAULT NULL,
    phone VARCHAR(20) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    foreign_key (DeviceID) REFERENCES DeviceID(device_id)
);
CREATE TABLE DeviceID (
    id INT AUTO_INCREMENT PRIMARY KEY,
    device_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE EnergyCollected (
    id INT AUTO_INCREMENT PRIMARY KEY,
    device_id VARCHAR(255) NOT NULL,
    usage INT NOT NULL,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    period VARCHAR(50) NOT NULL,
    FOREIGN KEY (device_id) REFERENCES DeviceID(device_id)
);
CREATE TABLE WaterPurified (
    id INT AUTO_INCREMENT PRIMARY KEY,
    device_id VARCHAR(255) NOT NULL,
    usage INT NOT NULL,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    period VARCHAR(50) NOT NULL,
    FOREIGN KEY (device_id) REFERENCES DeviceID(device_id)
);
CREATE TABLE EnergyUsage (
    id INT AUTO_INCREMENT PRIMARY KEY,
    device_id VARCHAR(255) NOT NULL,
    usage INT NOT NULL,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    period VARCHAR(50) NOT NULL,
    FOREIGN KEY (device_id) REFERENCES DeviceID(device_id)
);